FROM acr.aishu.cn/dual-mass-engine-gateway/nginx:latest

RUN rm -f /etc/nginx/conf.d/default.conf

COPY frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
